### ISSUE TITLE
Collection display

### ISSUE THREAD

**Issue by koneilluz** [jaguillette/hvd-dh-omeka-theme#12]
I just populated a Collection with 39 Items. When I [go to the collection page](http://dighist.fas.harvard.edu/projects/crimeaproject/collections/show/4) only 10 Items display on the screen. If you didn't know any better you would have no idea there are 29 more Items to view. There might be a more elegant solution than a scrollable list, but such a thing would do (see for example: http://gothicpast.com/items/browse?collection=2).

**Comment by koneilluz** [comment]
The other nice tweak on the Gothic Past site is that the Collections landing page does not include the Items themselves: only the Collection description, at the bottom of which you can "go to the Items in the Collection."

**Comment by jaguillette** [comment]
Imitating the Gothic Past model seems like the best way forward, linking to a page with the whole collection. I'm currently just figuring out how best to present that page, ideally including some previews of items.
