### ISSUE TITLE
Item display

### ISSUE THREAD

**Issue by koneilluz** [jaguillette/hvd-dh-omeka-theme#13]
In cases where Items do not have associated Files, could we adjust the display such that Item Relations and Tags appear in the right-hand column, next to the Dublin Core/Item Type fields? Perhaps the related Collections list as well?
An example of an Item that would benefit from such a rearrangement: http://dighist.fas.harvard.edu/projects/crimeaproject/items/show/182

**Comment by koneilluz** [comment]
Collection-level example here: http://dighist.fas.harvard.edu/projects/crimeaproject/items/browse?collection=4

**Comment by jaguillette** [comment]
For the collections case, I hacked on the plugin a bit to put that information on the browse items page. I had it only display the first three relations on that page, with a trailing ellipsis to indicate more relations if there are any. How is that functionality-wise?

**Comment by koneilluz** [comment]
That works nicely. Once I've uploaded (and curated) more content we can come back to this and see if we need to make adjustments. Thank you!
