### ISSUE TITLE
Multi-tag browsing

### ISSUE THREAD

**Issue by jaguillette** [jaguillette/hvd-dh-omeka-theme#15]
It would be great if there were an easy way to browse by multiple tags simultaneously. It's supported in that you can construct multi-tag urls for browse pages that work, but there's no front end for it right now.

**Comment by jaguillette** [comment]
I modified the "tags" pages for Items and Exhibits with a little bit of Javascript magic, and got an interface for selecting multiple tags from those pages. You can still click on a tag to browse by that tag, but each tag now has a checkbox next to it. All checked tags can be applied with a button on the bottom of the page.

**Comment by koneilluz** [comment]
Magical. Thank you.
