### ISSUE TITLE
Neatline timeline

### ISSUE THREAD

**Issue by koneilluz** [jaguillette/hvd-dh-omeka-theme#18]
The default timeline bar is not centered and/or does not extend evenly across the bottom of the map. 
[See here](http://dighist.fas.harvard.edu/projects/beautifulspaces/neatline/show/dachamap) for example. What can we do to make this more aesthetically pleasing?

**Comment by jaguillette** [comment]
Are you going to use Waypoints in this exhibit? It looks like Waypoints is enabled, so the styling is leaving space for them. If Waypoints isn't enabled, the timeline will stretch across the entire bottom of the map.

**Comment by jaguillette** [comment]
Timeline extends across bottom when waypoints are not enabled, but leaves space for waypoints when they are.
