### ISSUE TITLE
Neatline iframes

### ISSUE THREAD

**Issue by koneilluz** [jaguillette/hvd-dh-omeka-theme#19]
Just a follow-up to our conversation: if you could fandangle a way to produce iframe embed codes (that is probably not the right combination of words, but you know what I mean) for Neatlines, that would be amazing. That way we could embed bits of Neatline as "files" for Omeka Items.

**Comment by jaguillette** [comment]
I've added an embed code to the bottom center of the fullscreen Neatline display, so you can copy it and embed Neatline exhibits wherever you like. You can also change the width and height of the Neatline embed by tweaking the iframe code.
